Part1
jdurnil/PFMCPP_Project3 pull request #1
Opened 2023-03-19 15:06 UTC by jdurnil

2023-03-26 22:55 UTC, matkatmusic requested changes

2023-03-26 22:55 UTC, matkatmusic commented on main.cpp
> +    Burner burners[4];
Arrays have not been covered yet.
remove this, use a single instance
- [ ] revise

2023-03-26 22:55 UTC, matkatmusic commented on main.cpp
> +        float classGrade(Student student, std::string className = "English");
`classGrade` does not describe an action
- [ ] revise

2023-03-26 22:55 UTC, matkatmusic commented on main.cpp
> +    std::string grade="11";
add space around `=` to make the code more readable
- [ ] revise

2023-03-26 22:55 UTC, matkatmusic commented on main.cpp
> +*/
Where is your 10th UDT that is uses instances of UDTS 5-9 as its 5 properties?
- [ ] revise

2023-03-26 22:55 UTC, matkatmusic commented on main.cpp
> +    float collectPlay(float hourlyWage);
I'm marking this because:
1. your plain-english description is not an action, but is an ability or describes a state OR
2. the plain-english description is fine but the function name doesn't match OR
3. The way you wrote the name doesn't conform to the course coding standard:
    use `camelCase` for variable and function names.
    Type Names begin with a Capitalized first letter. All other symbols begin with a lower-case first letter.
- [ ] revise

2023-03-26 22:55 UTC, matkatmusic commented on main.cpp
> +
since you can't come up with 5 properties, this object is a bad choice
Choose a different object that can have 5 properties and 3 actions
- [ ] revise

2023-03-26 22:55 UTC, matkatmusic commented on main.cpp
> +    float amountTimeLeft = 234.5f;
Is this displaying minutes/seconds/hours?  
Variable names need to convey information, so be more specific with your variable name
- [ ] revise

2023-03-26 22:55 UTC, matkatmusic commented on main.cpp
> +    float currentTime = 110.6f;
Is this displaying minutes/seconds/hours?  
Variable names need to convey information, so be more specific with your variable name
- [ ] revise

2023-03-27 20:57 UTC, jdurnil commented on main.cpp
> +    float collectPlay(float hourlyWage);
You weren't specific here which I would rather. It's camel case, its an action etc.. it meets all requirements the only thing i can think of is it was misspelled. Please tell me what is wrong with my code in the future and don't give me one of three options that don't even fit the problem,

2023-03-27 21:04 UTC, jdurnil commented on main.cpp
> +    float currentTime = 110.6f;
Since I don't have a time type and I don't have something like datetime.now i am using number of minutes past midnight. I have variables like currentTime in a significant basis in normal coding how do you suggest i handle it and name it without any other capabilities

2023-03-27 22:11 UTC, matkatmusic approved these changes

2023-03-27 22:12 UTC, merged